print("Please enter the number of lives.")
number_of_lives = int(input())
print("Please enter the energy level.")
energy_level = int(input())
print("Please enter the shield level.")
shield_level = int(input())
print()
print("Health has been set")
print()
print()
print()
print("Lives:", number_of_lives * "♥")
print("Energy:", energy_level * "♦")
print("Shield:", shield_level * "♠")