print("How many mountains should I display?")
display_mountains = int(input())
print("\nDisplaying...")
for count in range (display_mountains):
    print("           __")
    print("          /  \_  ")
    print("         /^    \ ")
    print("        /  ^    \_ ")
    print("      _/ ^ ^     ^\ ")
    print("     /  ^     ^    \ ")
print("\n\n Done!")